### ISSUE TITLE
#US04 Como equipo de desarrollo debemos crear una Landing Page para informar sobre las funciones y servicios que brinda la plataforma.

### ISSUE THREAD

**Issue by diego50to** [pgCatamarca2021fs/aula2-grupoa-team-2a#15]

**Comment by ingfglopez** [comment]
- [x] #739
- [ ] https://github.com/octo-org/octo-repo/issues/740
- [ ] Add delight to the experience when all tasks are complete :tada:

**Comment by diego50to** [comment]
[] TK02 Crear la hoja de estilos CSS

**Comment by mefuentes** [comment]
Modifique el propósito de la Landing Page
